GET http://localhost:9000/api/trading/commissions
Accept: application/json

###
PUT http://localhost:9000/api/trading/close
Content-Type: application/json

{
  "ids": ["3","4"],
  "is_open": false
}

###
GET http://localhost:9000/api/trading?dateStart=2022-01-28&dateEnd=2022-01-31
Accept: application/json

###
GET http://localhost:9000/api/trading
Accept: application/json

###
POST http://localhost:9000/api/trading
Content-Type: application/json

{
  "tiker": "SBER",
  "type": "sell",
  "price": 254.3,
  "count": 5,
  "lot": 10,
  "commission": 0.04,
  "commission_type": "percent"
}

###
http://localhost:9000/api/health