GET http://localhost:9000/api/trading/tiker?tiker=BABA
Accept: application/json

###
GET http://localhost:9000/api/trading/summary/equity
Accept: application/json

###
GET http://localhost:9000/api/trading/commissions
Accept: application/json

###
PUT http://localhost:9000/api/trading/close
Content-Type: application/json

{
  "ids": ["3","4"],
  "is_open": false
}

###
GET http://localhost:9000/api/trading?showOpen=true&tikerType=equity
Accept: application/json

###
GET http://localhost:9000/api/trading
Accept: application/json

###
POST http://localhost:9000/api/trading
Content-Type: application/json

{
  "tiker": "SBER",
  "type": "sell",
  "price": 254.3,
  "count": 5,
  "lot": 10,
  "commission": 0.04,
  "commission_type": "percent"
}

###
POST http://localhost:9000/api/futures
Content-Type: application/json

{
  "tiker": "VTBR-3.22",
  "is_open": true,
  "warranty_provision": 1000,
  "count": 2,
  "commission": 10,
  "commission_type": "fix_price"
}

###
GET http://localhost:9000/api/futures
Content-Type: application/json

###
PUT http://localhost:9000/api/futures/1
Content-Type: application/json

{
  "margin": 1.3,
  "is_open": false
}

###
GET http://localhost:9000/api/futures/summary
Accept: application/json

###
http://localhost:9000/api/health